 name = "byanisaputri-mua"
 compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
 
 # For static site deployment to Cloudflare Pages
 # Deploy with: bunx wrangler pages deploy dist
pages_build_output_dir = "dist"
